### PR TITLE
WIP - switch to oauth2 client for token fetch

### PR DESCRIPTION
**Pull request by zachgersh**
Going to have this hang out here for a bit:

### left to do

- [ ] move decoding jwt / verification into handler
- [ ] slight http client refactor on initialize

### CODE REVIEW

**Comment by jeffpak** [comment]
@zachgersh ping ping ping

**Comment by zachgersh** [comment]
clay has been working on this with me :D

**Comment by cameronmoreau** [comment]
Hey @KauzClay and @zachgersh 
Are you still working on this PR?

cc @ameowlia

**Comment by ameowlia** [comment]
Hi all, 

We are closing this issue due to inactivity. If this is still an issue, please feel free to reopen with more information about its impact.

Thanks, 
@ameowlia and @mike1808 , CF Networking Program Members

**Pull request closed without merging**
