### PR TITLE
Ensure router group with available TCP port

### PR DESCRIPTION
**Pull request by ssapra**
First pass of merging the logic from the service-gateway library into the routing-api.

[#175028198](https://www.pivotaltracker.com/story/show/175028198)

Signed-off-by: Shaan Sapra <shsapra@pivotal.io>

### CODE REVIEW

**Comment by ameowlia** [comment]
Hi @ssapra, It looks like you are continuing to push commits. Please let us know when you are done and want us to review. 

Thanks!

**Comment by colins** [comment]
Hi @ameowlia we're ready for that review now, thanks.
We're struggling to add the EasyCLA auth. We'll add it later.

**Comment by ameowlia** [comment]
Hi @colins and @ssapra, 

Can you provide any docs or background on the "why" you are doing this, just so I can better understand the use cases you are working towards? Also do you have any api docs something [like these](https://github.com/cloudfoundry/routing-api/blob/main/docs/api_docs.md)?

**Comment by ssapra** [comment]
Hi @ameowlia ,

That's totally fair, we should've added some more context in the description.

In order to support off platform access to a service instance on the foundation, we have decided to use the TCP router provided in cf-deployment. To use the feature, we ask operators to decide on a port range that they would like to allocate for service instances of a specific database (i.e. MySQL or RabbitMQ). 

When the CF developer chooses to provision/update a service instance that has enabled off platform access, we need to be able to find which ports are available in the port range that the operator has chosen. To that end, we've built a utility function that is able to list all router groups, determine which ports are already reserved, and then find the first port that is available to be reserved for the service instance.

Initially this utility function was used solely by the RabbitMQ team. Now we on MySQL have begun to use it as well and we are trying to avoid proliferation of repositories whose sole purpose is to interact with the internals of the `routing-api` via the client. We think that this small utility function can be added to the routing-api so that it can be maintained alongside other similar functions.

**Comment by ansd** [comment]
To add a bit more context to the Service Gateway feature:

A blog post describing the Service Gateway ( aka. Off Platform) feature can be found [here](https://tanzu.vmware.com/content/practitioners/connect-your-external-workloads-via-rabbitmq-with-service-gateway-access).
More information on how this feature is currently used in the RabbitMQ Tile and an architecture diagram can be found [here](https://docs.pivotal.io/rabbitmq-cf/1-20/service-gateway-access.html).

This PR intends to simplify and to reduce the number of dependencies needed for the Service Gateway feature by moving existing logic from [the service-gateway Go module](https://github.com/pivotal/service-gateway) (not open source) to the routing-api such that the service-gateway Go module doesn't need to exist anymore.

**Comment by ameowlia** [comment]
Thank you for the context @ssapra and @ansd, that really helps. In order to help us try out these endpoints for ourselves, can you please add corresponding api docs to this file - https://github.com/cloudfoundry/routing-api/blob/main/docs/api_docs.md .

Thank you!

**Comment by ssapra** [comment]
We aren't adding or changing any endpoints. We intend to vendor the `routing-api` and invoke the client directly in our code.

**Comment by ameowlia** [comment]
Gotcha. Thanks @ssapra. I have added [this story](https://www.pivotaltracker.com/story/show/175126400) to our backlog to review & comment & merge. Is there any time pressure on this?

**Comment by ssapra** [comment]
There's no time pressure. For now both teams are using the service-gateway library so we're unblocked in making progress.

**Pull request merged**
